### ISSUE TITLE
现在是18.05了，这个master能用不

### ISSUE THREAD

**Issue by daishenghao** [denverdino/k8s-for-docker-desktop#1]

**Comment by daishenghao** [comment]
我自己试了下，没效果，估计images要更新下，问下这些images的版本你是怎么知道的

**Comment by denverdino** [comment]
你点about页面，上面写的是哪个Kubernetes版本？
18.04是Kubernetes: v1.9.6

**Comment by daishenghao** [comment]
我docker是 edge 18.05    k8s也是v1.9.6 那应该也可以用的  我再试试

**Comment by daishenghao** [comment]
OK 我在另外一台电脑上18.05用你的sh可以了 估计是那台电脑有问题
